const path = require('path');
const fs = require('fs');

const readme_path = path.join(__dirname, '../README.md');
const readme_relative_path = path.relative(process.cwd(), readme_path);

let readme_contents = fs.readFileSync(readme_path, 'utf8').toString().trim();

const API_HEADER = '# API';

let [readme_without_api] = readme_contents.split(API_HEADER);
readme_without_api = readme_without_api.trim();

let docs_content = fs
	.readFileSync(path.join(__dirname, '../temp-api.md'), 'utf8')
	.toString()
	.trim();

const new_readme = `${readme_without_api}

${API_HEADER}

> These are autogenerated from JSDoc comments in the source code.

${docs_content}
`;

fs.writeFileSync(readme_path, new_readme);

console.log(`Overwrote "${readme_relative_path}" with updated docs.`);
console.log(`You can review the changes and commit them.`);
